language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t srinivasdocker/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true srinivasdocker/docker-react npm run test -- --coverage 
