sudo: required
services:
        - docker

before_install:
        - docker build -t srinivasdocker/docker-react -f Dockerfile.dev .

script:
        - docker run srinivasdocker/docker-react npm run test -- --coverage
