language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t srinivasdocker/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true srinivasdocker/docker-react npm run test -- --coverage 

deployment:
        provider: elasticbeanstalk
        region: "us-east-1"
        app: "docker"
        env: "Docker-env"
        bucket_name: "elasticbeanstalk-us-east-1-123456789"
        bucket_path: "docker"   #will be same as app name
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        access_secret_key: $AWS_SECRET_KEY
